version: '3.9'

services:
  service1:
    build: ./service_1
    container_name: service1
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 30s
      timeout: 10s
      retries: 5

  service2:
    build: ./service_2
    container_name: service2
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
